# Generated by Django 3.2.4 on 2021-07-07 01:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/imgsubidas/', verbose_name='image')),
                ('nombre', models.CharField(max_length=80, verbose_name='nombre')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='telefono')),
                ('correo', models.EmailField(max_length=254, verbose_name='correo')),
                ('pais', models.CharField(max_length=30, verbose_name='pais')),
                ('password', models.CharField(max_length=20, verbose_name='contraseña')),
                ('moneda', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='moneda')),
            ],
        ),
    ]
