# Generated by Django 3.2.4 on 2021-07-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_proveedor_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='password',
            field=models.CharField(max_length=20, verbose_name='contrasenna'),
        ),
    ]
