# Generated by Django 3.2.4 on 2021-07-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_proveedor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
