# Generated by Django 3.2.4 on 2021-07-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_proveedor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='direccion'),
        ),
    ]
