# Generated by Django 3.2.4 on 2021-07-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_proveedor_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='moneda',
            field=models.IntegerField(choices=[[0, 'Dolares'], [1, 'Pesos']]),
        ),
    ]
