# Generated by Django 3.2.4 on 2021-07-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_proveedor_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='image'),
        ),
    ]
