# Generated by Django 3.2.4 on 2021-07-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_proveedor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='fotos/', verbose_name='image'),
        ),
    ]
